# Generated by Django 5.2.5 on 2025-09-15 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_libro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(null=True, upload_to='portadas_libros'),
        ),
    ]
