# Generated by Django 5.2.5 on 2025-09-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_de_publicacion',
            field=models.DateField(),
        ),
    ]
