# Generated by Django 5.2.5 on 2025-09-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_libro_fecha_de_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_de_publicacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
