# Generated by Django 5.2.5 on 2025-09-15 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_alter_libro_fecha_de_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='fecha_de_publicacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
