# Generated by Django 5.2.5 on 2025-09-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_alter_libro_fecha_de_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.CharField(max_length=80),
        ),
    ]
